name: Docker Image CI

on:
  push:
    branches: [ master ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: 20101988/ping-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
